# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            nam.nd
tagline:          'Software Engineer'
description:      'Passionate about coding<br />Enjoy solving problems<br />Love building things'
url:              https://namnd.github.io
baseurl:          /

paginate:         5


# Custom vars
