# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            namnd.com
tagline:          'Software Engineer'
description:      ''
url:              https://namnd.github.io
baseurl:          /

paginate:         5


# Custom vars
